# Generated by Django 4.2.16 on 2025-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoapp', '0002_alter_taskmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
